export interface CountryOption {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: CountryOption[] = [
  { code: "+569", name: "Chile", flag: "cl" },
  { code: "+1", name: "United States", flag: "us" },
  { code: "+52", name: "Mexico", flag: "mx" },
  { code: "+55", name: "Brazil", flag: "br" },
  { code: "+57", name: "Colombia", flag: "co" },
  { code: "+54", name: "Argentina", flag: "ar" },
  { code: "+591", name: "Bolivia", flag: "bo" },
  { code: "+56", name: "Chile", flag: "cl" },
  { code: "+506", name: "Costa Rica", flag: "cr" },
  { code: "+53", name: "Cuba", flag: "cu" },
  { code: "+593", name: "Ecuador", flag: "ec" },
  { code: "+503", name: "El Salvador", flag: "sv" },
  { code: "+502", name: "Guatemala", flag: "gt" },
  { code: "+509", name: "Haiti", flag: "ht" },
  { code: "+504", name: "Honduras", flag: "hn" },
  { code: "+876", name: "Jamaica", flag: "jm" },
  { code: "+595", name: "Paraguay", flag: "py" },
  { code: "+51", name: "Peru", flag: "pe" },
  { code: "+597", name: "Suriname", flag: "sr" },
  { code: "+598", name: "Uruguay", flag: "uy" },
  { code: "+58", name: "Venezuela", flag: "ve" },
  { code: "+501", name: "Belize", flag: "bz" },
  { code: "+246", name: "Barbados", flag: "bb" },
  { code: "+1-441", name: "Bermuda", flag: "bm" },
  { code: "+1-345", name: "Cayman Islands", flag: "ky" },
  { code: "+1-767", name: "Dominica", flag: "dm" },
  { code: "+1-809", name: "Dominican Republic", flag: "do" },
  { code: "+1-473", name: "Grenada", flag: "gd" },
  { code: "+1-876", name: "Jamaica", flag: "jm" },
  { code: "+1-664", name: "Montserrat", flag: "ms" },
  { code: "+1-869", name: "Saint Kitts and Nevis", flag: "kn" },
  { code: "+1-758", name: "Saint Lucia", flag: "lc" },
  { code: "+1-784", name: "Saint Vincent and the Grenadines", flag: "vc" },
  { code: "+1-868", name: "Trinidad and Tobago", flag: "tt" },
  { code: "+1-649", name: "Turks and Caicos Islands", flag: "tc" },
  { code: "+1-284", name: "British Virgin Islands", flag: "vg" },
  { code: "+1-340", name: "U.S. Virgin Islands", flag: "vi" },
  { code: "+44", name: "United Kingdom", flag: "gb" },
  { code: "+33", name: "France", flag: "fr" },
  { code: "+49", name: "Germany", flag: "de" },
  { code: "+39", name: "Italy", flag: "it" },
  { code: "+34", name: "Spain", flag: "es" },
  { code: "+31", name: "Netherlands", flag: "nl" },
  { code: "+32", name: "Belgium", flag: "be" },
  { code: "+41", name: "Switzerland", flag: "ch" },
  { code: "+43", name: "Austria", flag: "at" },
  { code: "+45", name: "Denmark", flag: "dk" },
  { code: "+46", name: "Sweden", flag: "se" },
  { code: "+47", name: "Norway", flag: "no" },
  { code: "+48", name: "Poland", flag: "pl" },
  { code: "+351", name: "Portugal", flag: "pt" },
  { code: "+353", name: "Ireland", flag: "ie" },
  { code: "+354", name: "Iceland", flag: "is" },
  { code: "+355", name: "Albania", flag: "al" },
  { code: "+356", name: "Malta", flag: "mt" },
  { code: "+357", name: "Cyprus", flag: "cy" },
  { code: "+358", name: "Finland", flag: "fi" },
  { code: "+359", name: "Bulgaria", flag: "bg" },
  { code: "+36", name: "Hungary", flag: "hu" },
  { code: "+370", name: "Lithuania", flag: "lt" },
  { code: "+371", name: "Latvia", flag: "lv" },
  { code: "+372", name: "Estonia", flag: "ee" },
  { code: "+373", name: "Moldova", flag: "md" },
  { code: "+374", name: "Armenia", flag: "am" },
  { code: "+375", name: "Belarus", flag: "by" },
  { code: "+376", name: "Andorra", flag: "ad" },
  { code: "+377", name: "Monaco", flag: "mc" },
  { code: "+378", name: "San Marino", flag: "sm" },
  { code: "+380", name: "Ukraine", flag: "ua" },
  { code: "+381", name: "Serbia", flag: "rs" },
  { code: "+382", name: "Montenegro", flag: "me" },
  { code: "+383", name: "Kosovo", flag: "xk" },
  { code: "+385", name: "Croatia", flag: "hr" },
  { code: "+386", name: "Slovenia", flag: "si" },
  { code: "+387", name: "Bosnia and Herzegovina", flag: "ba" },
  { code: "+389", name: "North Macedonia", flag: "mk" },
  { code: "+420", name: "Czech Republic", flag: "cz" },
  { code: "+421", name: "Slovakia", flag: "sk" },
  { code: "+423", name: "Liechtenstein", flag: "li" },
];
